In [19]:
import pandas as pd
import seaborn as sns
import numpy as np

In [26]:
df = sns.load_dataset("penguins")

In [27]:
print(df.isnull().sum())

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [28]:
df['species'].fillna(df['species'].mode()[0], inplace=True)
df['sex'].fillna(df['sex'].mode()[0], inplace=True)

In [29]:
df.drop_duplicates(inplace=True)

In [30]:
df = pd.get_dummies(df, columns=['species', 'sex'], drop_first=True)

In [31]:
df = df[(np.abs(stats.zscore(df['body_mass_g'])) < 3)]

In [36]:
import pandas as pd

data = {'A': [1, 2, None, 4], 'B': [None, 2, 3, 4]}
df = pd.DataFrame(data)
df['A'].fillna(df['A'].mean(), inplace=True)
df['B'].fillna(df['B'].mean(), inplace=True)
df

          A    B
0  1.000000  3.0
1  2.000000  2.0
2  2.333333  3.0
3  4.000000  4.0

In [37]:
data = {'A': [1, 2, 2, 4], 'B': [5, 6, 6, 8]}
df = pd.DataFrame(data)
df.drop_duplicates(inplace=True)
df

   A  B
0  1  5
1  2  6
3  4  8

In [43]:
import numpy as np
from scipy import stats

data = {'A': [1, 2, 3, 4, 100]}
df = pd.DataFrame(data)
df = df[(np.abs(stats.zscore(df['A'])) < 3)]
df

     A
0    1
1    2
2    3
3    4
4  100

In [44]:
data = {'Date': ['2023-01-01', '2023-02-01']}
df = pd.DataFrame(data)
df['Date'] = pd.to_datetime(df['Date'])
df

        Date
0 2023-01-01
1 2023-02-01