In [18]:
#Mirage Shrestha Week 4 Assignment
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn import linear_model
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [5]:
df = sns.load_dataset("mpg") 
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [7]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [8]:
X = df.drop(columns = ["mpg", "origin", "name"])
X

     cylinders  displacement  horsepower  weight  acceleration  model_year
0            8         307.0       130.0    3504          12.0          70
1            8         350.0       165.0    3693          11.5          70
2            8         318.0       150.0    3436          11.0          70
3            8         304.0       150.0    3433          12.0          70
4            8         302.0       140.0    3449          10.5          70
..         ...           ...         ...     ...           ...         ...
393          4         140.0        86.0    2790          15.6          82
394          4          97.0        52.0    2130          24.6          82
395          4         135.0        84.0    2295          11.6          82
396          4         120.0        79.0    2625          18.6          82
397          4         119.0        82.0    2720          19.4          82

[398 rows x 6 columns]

In [10]:
y=df.mpg

In [11]:
X.isnull().sum()

cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
dtype: int64

In [12]:
X = X.fillna(0)

In [13]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cylinders     398 non-null    int64
 1   displacement  398 non-null    float64
 2   horsepower    398 non-null    float64
 3   weight        398 non-null    int64
 4   acceleration  398 non-null    float64
 5   model_year    398 non-null    int64
dtypes: float64(3), int64(3)
memory usage: 18.8 KB

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y)
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [17]:
y_predict = model.predict(X_test)
mean_absolute_error(y_test, y_predict)

2.589188969042939